/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        legis: {
          navy: '#0B172D',
          'navy-hover': '#152542',
          'navy-subtle': '#E8ECF2',
          blue: '#1B62E3',
          'blue-hover': '#1550BA',
          'blue-subtle': '#EBF2FC',
          orange: '#CA7B20',
          'orange-hover': '#AF6818',
          'orange-subtle': '#FDF4EB',
          light: '#F3F5F9',
          gray: '#68768A',
          'gray-subtle': '#F0F2F5',
          'gray-border': '#E2E8F0',
        },
        ios: {
          blue: '#1B62E3',
          'blue-hover': '#1550BA',
          'blue-subtle': '#EBF2FC',
          navy: '#0B172D',
          'navy-hover': '#152542',
          green: '#34C759',
          'green-subtle': '#EBF9EE',
          indigo: '#5856D6',
          'indigo-subtle': '#EEEEFC',
          red: '#FF3B30',
          'red-subtle': '#FFECEB',
          orange: '#CA7B20',
          'orange-subtle': '#FDF4EB',
          amber: '#CA7B20',
          gray: {
            50: '#F9FAFB',
            100: '#F3F5F9',
            200: '#E2E8F0',
            300: '#CBD5E1',
            400: '#94A3B8',
            500: '#68768A',
            600: '#475569',
            700: '#334155',
            800: '#1E293B',
            900: '#0B172D',
            950: '#060D1A',
          },
          dark: {
            bg: '#0B172D',
            card: '#121F38',
            elevated: '#182949',
            border: '#22365D',
          },
        },
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          'SF Pro',
          'Helvetica Neue',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          'SF Pro',
          'sans-serif',
        ],
      },
      fontSize: {
        'ios-large-title': ['34px', { lineHeight: '41px', letterSpacing: '-0.4px', fontWeight: '700' }],
        'ios-title1': ['28px', { lineHeight: '34px', letterSpacing: '-0.3px', fontWeight: '700' }],
        'ios-title2': ['22px', { lineHeight: '28px', letterSpacing: '-0.2px', fontWeight: '700' }],
        'ios-title3': ['20px', { lineHeight: '25px', letterSpacing: '-0.1px', fontWeight: '600' }],
        'ios-headline': ['17px', { lineHeight: '22px', letterSpacing: '-0.4px', fontWeight: '600' }],
        'ios-body': ['17px', { lineHeight: '22px', letterSpacing: '-0.4px', fontWeight: '400' }],
        'ios-callout': ['16px', { lineHeight: '21px', letterSpacing: '-0.3px', fontWeight: '400' }],
        'ios-subhead': ['15px', { lineHeight: '20px', letterSpacing: '-0.2px', fontWeight: '400' }],
        'ios-footnote': ['13px', { lineHeight: '18px', letterSpacing: '-0.1px', fontWeight: '400' }],
        'ios-caption1': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'ios-caption2': ['11px', { lineHeight: '13px', fontWeight: '400' }],
      },
      borderRadius: {
        'ios-xs': '6px',
        'ios-sm': '10px',
        'ios-md': '14px',
        'ios-lg': '18px',
        'ios-xl': '24px',
        'ios-2xl': '32px',
      },
      boxShadow: {
        'ios-xs': '0 1px 2px rgba(0, 0, 0, 0.04)',
        'ios-sm': '0 2px 6px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.02)',
        'ios-md': '0 6px 16px rgba(0, 0, 0, 0.06), 0 2px 4px rgba(0, 0, 0, 0.02)',
        'ios-lg': '0 12px 32px rgba(0, 0, 0, 0.08), 0 4px 8px rgba(0, 0, 0, 0.03)',
        'ios-sheet': '0 -8px 30px rgba(0, 0, 0, 0.12)',
      },
      transitionTimingFunction: {
        'ios': 'cubic-bezier(0.25, 1, 0.5, 1)',
        'ios-spring': 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  plugins: [],
};